# Generated by Django 3.0.2 on 2020-01-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
