# Generated by Django 3.0.2 on 2020-01-29 02:46

import os
from django.db import migrations
from sys import path
from django.core import serializers

fixture_dir = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'AppUsersInitData.json'


def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)

    fixture = open(fixture_file, 'rb')
    objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
    for obj in objects:
        obj.save()
    fixture.close()


def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."

    MyModel = apps.get_model("quickstart", "AppUser")
    MyModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200128_2026'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
